version: "3.8"
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PRODUCTION=${PRODUCTION}
      - CLIENT_HOST=${CLIENT_HOST}
      - STRIP_PUBLISHABLE_KEY=${STRIP_PUBLISHABLE_KEY}
      - STRIP_SECRET_KEY=${STRIP_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_PORT=${SUPABASE_PORT}
      - SUPABASE_DBNAME=${SUPABASE_DBNAME}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./cert.key:/etc/nginx/cert.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
