services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PRODUCTION=${PRODUCTION}
      - CLIENT_HOST=${CLIENT_HOST}
      - STRIP_PUBLISHABLE_KEY=${STRIP_PUBLISHABLE_KEY}
      - STRIP_SECRET_KEY=${STRIP_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_PORT=${SUPABASE_PORT}
      - SUPABASE_DBNAME=${SUPABASE_DBNAME}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - MY_EMAIL=${MY_EMAIL}
      - DOMAIN_EMAIL=${DOMAIN_EMAIL}
      - AES_KEY=${AES_KEY}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
