# Generated by Django 5.0.7 on 2024-07-20 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0003_alter_family_family_name_alter_invitation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphemeralTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ephemeral_task_name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (5, 'Level 3'), (10, 'Level 4'), (15, 'Level 5'), (30, 'Level 6'), (60, 'Level 7'), (120, 'Level 8')])),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ephemeral_task', to='tasks_api.family')),
            ],
            options={
                'db_table': 'ephemeral_task',
            },
        ),
    ]
