# Generated by Django 5.0.7 on 2024-07-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0004_ephemeraltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeraltask',
            name='member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ephemeral_task', to='tasks_api.member'),
        ),
    ]
