# Generated by Django 5.0.7 on 2024-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0006_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='FREE', max_length=10),
        ),
    ]
