# Generated by Django 5.0.7 on 2024-07-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0007_family_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='subscription_plan',
        ),
    ]
