# Generated by Django 5.0.7 on 2024-07-26 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0008_remove_family_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='FREE', max_length=10)),
                ('locale', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=10)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_settings', to='tasks_api.family')),
            ],
            options={
                'db_table': 'family_settings',
            },
        ),
    ]
