# Generated by Django 5.0.7 on 2024-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0009_familysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familysettings',
            name='locale',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('de', 'German')], default='en', max_length=10),
        ),
    ]
